version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  nginx:
    image: nginx
    links:
      - api
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    image: node
    volumes:
      - ./api/:/app/
    working_dir: /app/
    command: bash -c "npm rebuild --update-binary bcrypt && npm run dev"
    ports:
      - "4321:80"
    restart: on-failure
    expose:
      - "80"
    links:
      - db
