version: '3.1'

services:
  nginx:
    image: nginx
    links:
      - api
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    image: node
    volumes:
      - ./api/:/app/
    working_dir: /app/
    command: npm start
    expose:
      - "80"
    links:
      - db