version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ~/db:/var/lib/mysql
  nginx:
    image: nginx
    links:
      - api
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    env_file:
    - ./api/.env
    image: node
    volumes:
      - ./api/:/app/
    working_dir: /app/
    restart: on-failure
    command: bash -c "npm install && npm run build && npm run start"
    expose:
      - "80"
    links:
      - db
