# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Luces' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Luces

  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'


  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'LucesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Luces-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Luces-tvOS

  target 'Luces-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
